name: Swift
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: set -o pipefail && time xcodebuild clean test -scheme MarkdownSyntax -sdk macosx -enableCodeCoverage YES | xcpretty
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
